# Generated by Django 2.2.24 on 2021-08-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Item',
        ),
    ]
